### ISSUE TITLE
Typo in script files

### ISSUE THREAD

**Issue by OxNinja** [lambdhack/yubuild_pgp#1]
Hey nice tool here!

But didn't you meant `YYYY.MM.DD-hh:mm` date format on both scripts?
https://github.com/lambdhack/yubuild_pgp/blob/682a9a4bf8baeb44b34d2dbabbdf744c68761948/overlay/root/renew_subkeys.sh#L5
https://github.com/lambdhack/yubuild_pgp/blob/682a9a4bf8baeb44b34d2dbabbdf744c68761948/overlay/root/generate_keys.sh#L8
Side note: you mixed french and english in comments for:
https://github.com/lambdhack/yubuild_pgp/blob/682a9a4bf8baeb44b34d2dbabbdf744c68761948/overlay/root/.gnupg/gpg.conf#L1

**Comment by lambdhack** [comment]
Thanks I didn't notice that :)
